package com.osrs_springboot_project.osrs_springboot_project.enums;

public enum OSRS_ACTIVITIES {
    LEAGUE_POINTS("League_Points"),
    DEADMAN_POINTS("Deadman_Points"),
    BOUNTY_HUNTER_HUNTER("Bounty_Hunter_Hunter"),
    BOUNTY_HUNTER_ROGUE("Bounty_Hunter_Rogue"),
    BOUNTY_HUNTER_HUNTER_LEGACY("Bounty_Hunter_Hunter_Legacy"),
    BOUNTY_HUNTER_ROGUE_LEGACY("Bounty_Hunter_Rogue_Legacy"),
    CLUE_SCROLLS("Clue_Scrolls"),
    BEGINNER_CLUES("Beginner_Clues"),
    EASY_CLUES("Easy_Clues"),
    MEDIUM_CLUES("Medium_Clues"),
    HARD_CLUES("Hard_Clues"),
    ELITE_CLUES("Elite_Clues"),
    MASTER_CLUES("Master_Clues"),
    LMS_RANK("LMS_Rank"),
    PVP_ARENA_RANK("PvP_Arena_Rank"),
    SOUL_WARS_ZEAL("Soul_Wars_Zeal"),
    RIFTS_CLOSED("Rifts_Closed"),
    COLOSSEUM_GLORY("Colosseum_Glory"),
    COLLECTIONS_LOGGED("Collections_Logged"),
    ABYSSAL_SIRE("Abyssal_Sire"),
    ALCHEMICAL_HYDRA("Alchemical_Hydra"),
    AMOXLIATL("Amoxliatl"),
    ARAXXOR("Araxxor"),
    ARTIO("Artio"),
    BARROWS_CHESTS("Barrows_Chests"),
    BRYOPHYTA("Bryophyta"),
    CALLISTO("Callisto"),
    CALVARION("Calvarion"),
    CERBERUS("Cerberus"),
    CHAMBERS_OF_XERIC("Chambers_of_Xeric"),
    CHAMBERS_OF_XERIC_CHALLENGE_MODE("Chambers_of_Xeric_Challenge_Mode"),
    CHAOS_ELEMENTAL("Chaos_Elemental"),
    CHAOS_FANATIC("Chaos_Fanatic"),
    COMMANDER_ZILYANA("Commander_Zilyana"),
    CORPOREAL_BEAST("Corporeal_Beast"),
    CRAZY_ARCHAEOLOGIST("Crazy_Archaeologist"),
    DAGANNOTH_PRIME("Dagannoth_Prime"),
    DAGANNOTH_REX("Dagannoth_Rex"),
    DAGANNOTH_SUPREME("Dagannoth_Supreme"),
    DERANGED_ARCHAEOLOGIST("Deranged_Archaeologist"),
    DUKE_SUCELLUS("Duke_Sucellus"),
    GENERAL_GRAARDOR("General_Graardor"),
    GIANT_MOLE("Giant_Mole"),
    GROTESQUE_GUARDIANS("Grotesque_Guardians"),
    HESPORI("Hespori"),
    KALPHITE_QUEEN("Kalphite_Queen"),
    KING_BLACK_DRAGON("King_Black_Dragon"),
    KRAKEN("Kraken"),
    KREE_ARRA("Kree_Arra"),
    KRIL_TSUTSAROTH("Kril_Tsutsaroth"),
    LUNAR_CHESTS("Lunar_Chests"),
    MIMIC("Mimic"),
    NEX("Nex"),
    NIGHTMARE("Nightmare"),
    PHOSANIS_NIGHTMARE("Phosanis_Nightmare"),
    OBOR("Obor"),
    PHANTOM_MUSPAH("Phantom_Muspah"),
    ROYAL_TITANS("Royal_Titans"),
    SARACHNIS("Sarachnis"),
    SCORPIA("Scorpia"),
    SCURRIUS("Scurrius"),
    SKOTIZO("Skotizo"),
    SOL_HEREDIT("Sol_Heredit"),
    SPINDEL("Spindel"),
    TEMPOROSS("Tempoross"),
    THE_GAUNTLET("The_Gauntlet"),
    THE_CORRUPTED_GAUNTLET("The_Corrupted_Gauntlet"),
    THE_HUEYCOATL("The_Hueycoatl"),
    THE_LEVIATHAN("The_Leviathan"),
    THE_WHISPERER("The_Whisperer"),
    THEATRE_OF_BLOOD("Theatre_of_Blood"),
    THEATRE_OF_BLOOD_HARD_MODE("Theatre_of_Blood_Hard_Mode"),
    THERMONUCLEAR_SMOKE_DEVIL("Thermonuclear_Smoke_Devil"),
    TOMBS_OF_AMASCUT("Tombs_of_Amascut"),
    TOMBS_OF_AMASCUT_EXPERT_MODE("Tombs_of_Amascut_Expert_Mode"),
    TZKAL_ZUK("TzKal_Zuk"),
    TZTOK_JAD("TzTok_Jad"),
    VARDORVIS("Vardorvis"),
    VENENATIS("Venenatis"),
    VETION("Vet_ion"),
    VORKATH("Vorkath"),
    WINTERTODT("Wintertodt"),
    ZALCANO("Zalcano"),
    ZULRAH("Zulrah");

    private String activityName;

    OSRS_ACTIVITIES(String activityName) {
        this.activityName = activityName;
    }

    public String getActivityname() {
        return this.activityName;
    }
}
